spring.application.name=padeJeux1

# Configuration de la base de données MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/padelplus
spring.datasource.username=root
spring.datasource.password=

# Configuration de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
